// Clean type aliases over the generated OpenAPI schema (src/generated/api.ts,
// regenerated by scripts/sync-types.sh — do not edit that file by hand).

import type { components } from "./generated/api.js";

type Schemas = components["schemas"];

export type SportEntry = Schemas["SportEntry"];
export type SportListResponse = Schemas["SportListResponse"];
export type StringListResponse = Schemas["StringListResponse"];

export type PlayerSummary = Schemas["PlayerSummary"];
export type PlayerDetail = Schemas["PlayerDetail"];
export type PlayerSeasonsResponse = Schemas["PlayerSeasonsResponse"];
export type PlayerSearchPage = Schemas["PlayerSearchPage"];

export type TeamSummary = Schemas["TeamSummary"];
export type TeamDetail = Schemas["TeamDetail"];
export type TeamPage = Schemas["TeamPage"];
export type RosterEntry = Schemas["RosterEntry"];
export type RosterPage = Schemas["RosterPage"];

export type TransferRecord = Schemas["TransferRecord"];
export type TransferListResponse = Schemas["TransferListResponse"];

export type MovementSubject = Schemas["MovementSubject"];
export type MovementEntry = Schemas["MovementEntry"];
export type MovementPage = Schemas["MovementPage"];

export type GameSummary = Schemas["GameSummary"];
export type GameFixture = Schemas["GameFixture"];
export type GamePage = Schemas["GamePage"];

export type TeamCoachEntry = Schemas["TeamCoachEntry"];
export type TeamCoachesResponse = Schemas["TeamCoachesResponse"];

export type ExportCreateRequest = Schemas["ExportCreateRequest"];
export type ExportCreateResponse = Schemas["ExportCreateResponse"];
export type ExportJobStatus = Schemas["ExportJobStatus"];
export type ExportListPage = Schemas["ExportListPage"];

export type PortalEntry = Schemas["PortalEntry"];
export type PortalPage = Schemas["PortalPage"];

export type QueryCreateResponse = Schemas["QueryCreateResponse"];
export type QueryRunStatus = Schemas["QueryRunStatus"];

export type AlertSummary = Schemas["AlertSummary"];
export type AlertListResponse = Schemas["AlertListResponse"];
export type AlertMatchEntry = Schemas["AlertMatchEntry"];
export type AlertMatchListResponse = Schemas["AlertMatchListResponse"];
export type AlertDeleteResponse = Schemas["AlertDeleteResponse"];
export type AlertCreateRequest = Schemas["AlertCreateRequest"];

export type PlayerSearchRequest = Schemas["PlayerSearchRequest"];
export type PublicQueryRequest = Schemas["PublicQueryRequest"];

export type ApiErrorDetail = Schemas["ApiErrorDetail"];
export type ApiErrorResponse = Schemas["ApiErrorResponse"];
